### ISSUE TITLE
Announce the repo

### ISSUE THREAD

**Issue by Eeems** [toltec-dev/toltec#15]
From what I can tell, we should probably do a proper rollout of this to the larger community. Here is what I think we need to do first before we can "announce":

- [x] Flush out documentation on how to create packages (#18).
- [x] Flush out user documentation for how to install/update (#19).
- [x] Get the stable repo actually stable.
- [x] Sort out the process (and document it) for getting things from testing to stable (#20).
- [ ] Update the community wiki (remarkablewiki.com) with information on this (And probably some of the standards we are starting to form).
- [x] Document philosophy/principles (#16).
- [x] Add security policy (#56 )
- [x] Add privacy policy (#58)

After that we should probably do the following to "announce":

- [x] Put together a nicer front page (or have it redirect to this github) (#21, #22).
- [ ] Post to the Subreddit.
- [ ] Post to the Facebook group.

**Comment by matteodelabre** [comment]
Another thing to do before announcing, as proposed by @raisjnn:

* [x] Document philosophy/principles (#16).

**Comment by Eeems** [comment]
Added to the list.

**Comment by raisjnn** [comment]
In terms of announcing, I'd be happy to:

* work on web pages and package listing
* post an announcement to reddit (since i've been talking  on reddit about wanting package manager + app store for about a month)

my ideal is that when we announce, we should have a single script they run to get opkg+toltec+nao+a launcher, then at that point they have enough UI to start installing packages directly from the tablet. it's fine if we can't hit this for the first announcement, though since we will probably target power users first.

**Comment by Eeems** [comment]
Added #55 to the list.

**Comment by matteodelabre** [comment]
Can this issue be merged in the milestone https://github.com/toltec-dev/toltec/milestone/1?

**Comment by Eeems** [comment]
There are a couple items in the list that don't have separate issues, so I think it deserves to stay open.

**Comment by matteodelabre** [comment]
Indeed. AFAICT, the remaining tasks are all related to actually making the announcement, so this issue should be the last one closed in the milestone.

**Comment by Eeems** [comment]
Should we also create a code of conduct?

**Comment by raisjn** [comment]
> Should we also create a code of conduct?

is there a standard one we can use?

**Comment by Eeems** [comment]
I believe there is a template.

**Comment by Eeems** [comment]
To follow up on this, iirc, when adding the CoC to oxide it gave me two templates to pick from.

**Comment by Eeems** [comment]
We should probably make some progress on the actual announcement of this?

**Comment by Eeems** [comment]
Should we close this? I'd say we are actually already announced.

**Comment by raisjn** [comment]
yeah, let's close
